// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlogService.proto

package com.example.wwy_blog.grpc.blog;

public interface BlogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BlogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
