// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlogService.proto

package com.example.wwy_blog.grpc.blog;

public final class BlogProto {
  private BlogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BlogService.proto\"\034\n\014HelloRequest\022\014\n\004n" +
      "ame\030\001 \001(\t\"\037\n\rHelloResponse\022\016\n\006result\030\001 \001" +
      "(\t\"\031\n\013BlogRequest\022\n\n\002id\030\001 \001(\005\"`\n\014BlogRes" +
      "ponse\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\020\n\010cate" +
      "gory\030\003 \001(\t\022\017\n\007context\030\004 \001(\t\022\022\n\ncreateTim" +
      "e\030\005 \001(\t24\n\005Hello\022+\n\010SayHello\022\r.HelloRequ" +
      "est\032\016.HelloResponse\"\0002;\n\013BlogService\022,\n\013" +
      "GetBlogById\022\014.BlogRequest\032\r.BlogResponse" +
      "\"\000B-\n\036com.example.wwy_blog.grpc.blogB\tBl" +
      "ogProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_BlogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BlogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlogRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_BlogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BlogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlogResponse_descriptor,
        new java.lang.String[] { "Id", "Title", "Category", "Context", "CreateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
