// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlogService.proto

package com.example.wwy_blog.grpc.blog;

public interface BlogsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.BlogsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.BlogResponse blogs = 1;</code>
   */
  java.util.List<com.example.wwy_blog.grpc.blog.BlogResponse> 
      getBlogsList();
  /**
   * <code>repeated .proto.BlogResponse blogs = 1;</code>
   */
  com.example.wwy_blog.grpc.blog.BlogResponse getBlogs(int index);
  /**
   * <code>repeated .proto.BlogResponse blogs = 1;</code>
   */
  int getBlogsCount();
  /**
   * <code>repeated .proto.BlogResponse blogs = 1;</code>
   */
  java.util.List<? extends com.example.wwy_blog.grpc.blog.BlogResponseOrBuilder> 
      getBlogsOrBuilderList();
  /**
   * <code>repeated .proto.BlogResponse blogs = 1;</code>
   */
  com.example.wwy_blog.grpc.blog.BlogResponseOrBuilder getBlogsOrBuilder(
      int index);
}
