// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlogService.proto

package com.example.wwy_blog.grpc.blog;

public interface BlogsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.BlogsRequest)
    com.google.protobuf.MessageOrBuilder {
}
