# 本地环境 :全部换成后缀为local的属性，注掉spring.redis.password
# 远程环境 :全部换成后缀为server的属性，打开spring.redis.password

env:
  mysql:
    host_local: localhost:3306
    host_server: 124.222.212.180:3306
    username: root
    password: 123456
  redis:
    host_local: 127.0.0.1
    host_server: 124.222.212.180
    password: 142857
    port: 6379

server:
  port: 8081


spring:
  redis:
    database: 0
    host: ${env.redis.host_server}
    port: ${env.redis.port}
    password: ${env.redis.password}
  datasource:
    url: jdbc:mysql://${env.mysql.host_server}/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${env.mysql.username}
    password: ${env.mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

grpc:
  client:
    grpc-server:
      address: static://124.222.212.180:9090
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
